# 端口号
server:
  port: 8099

# 定位页面的目录到static/下
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  main:
    allow-bean-definition-overriding: true
  ## 集成Redis
  redis:
    ## Redis服务器连接地址
    host: 43.228.66.144
    password: ESXo78IL5uqhWUyc
    ## Redis服务器连接端口
    port: 6379
    timeout: 5000
    ## Redis服务器连接db
    database: 0
    ## 连接超时时间（毫秒）
    lettuce:
      pool:
        ## 连接池中的最大连接数
        max-idle: 8
        ## 连接池中的最小连接数
        min-idle: 0
        ## 连接池中的最大空闲连接
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

# mongoDB配置
mongodb:
  imroom:
    host: 43.228.66.144
    port: 28018
    database: imRoom
  imapi:
    host: 43.228.66.144
    port: 28018
    database: imapi

im:
  api:
    uri: http://43.228.66.144:8092    #    uri: http://127.0.0.1:8092
  appConfig:
    apiKey: im

xmpp:
  api:
    uri: http://43.228.66.144:8093

rocketmq:
  # 生产者配置
  producer:
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    groupName: xmppProducer
    # 服务地址
    namesrvAddr: 43.228.66.144:9876
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2

fee-plat:
  fee-plat-group: xmppProducer
  fee-plat-topic: xmppMessage
  fee-account-tag: FeeAccountTag

logging:
  level:
    com.anji.plus.assessment.mapper: DEBUG